lib:
  name: name
  description: a wio project
  url:
  version: 0.0.1
  author:
  contributors: []
  license:
  platform: platform
  framework: []
  keywords: []
  board: [ALL]
  compile_flags: []
  ide: ide
  default_target: test

  targets:
    test:
      board: board
      compile_flags: []

libraries: