lib:
  name:
  description:
  url:
  version: 0.0.1
  author:
  contributors: []
  organization:
  license:
  platform:
  framework: []
  keywords: []
  board: [ALL]
  compile_flags: []
  ide: ide

targets:
  default: test
  created:
    test:
      board:
      compile_flags: []
