app:
  name: name
  ide: ide
  platform: platform
  framework: framework

targets:
  default: main
  main:
    board: board
    compile_flags: []

dependencies:
  name:
    url:
    branch: null
    compile_flags: []
