wio:
  name:
  description:
  ide:
  default_target: "test"

# this is core package information that is need to publish the package
package:
  version:
  authors:
  license:
  platform:
  framework:
  board:
  compile_flags:

# targets are executables that can be built and uploaded
# every wio application will have a main target, which runs by default
# user can add other targets to test on different boards and with different flags
tragets:
  test:
    board:
    framrwork:
    compile_flags:

# dependencies are the libraries your program depends on
# wio will pull the dependencies based on your platform and framework and will compile it
dependencies:
  #package1:
  #  version:
  #  compile_flags:
