builds:
  - main: cmd/wio/wio.go
    binary: wio
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archive:
  format: tar.gz

  replacements:
    386: i386
    amd64: x86_64

  format_overrides:
    - goos: windows
      format: zip

  files:
    - toolchain/**/*/

nfpm:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  vendor: Wio
  homepage: https://github.com/wio/wio
  maintainer: Deep Dhillon <deep@deepdhillon.com>
  description: An Iot Development Environment
  license: MIT
  formats:
  - deb
  - rpm
  dependencies:
  - cmake
  - make
  suggests:
  - git
  - node
  files:
    "toolchain/**/*": "/usr/share/wio/toolchain"

brew:
  name: wio

  github:
    owner: dhillondeep
    name: homebrew-wio

  commit_author:
    name: dhillondeep
    email: deep@deepdhillon.ca

  folder: Formula

  homepage: "https://github.com/wio/wio"
  description: "An Iot Development Environment"
  test: |
    system "#{bin}/wio --version"
  install: |
    prefix.install Dir["toolchain"]
    bin.install "wio"

scoop:
  bucket:
    owner: dhillondeep
    name: wio-bucket

  commit_author:
    name: Deep Dhillon
    email: deep@deepdhillon.ca

  homepage: "https://github.com/wio/wio"
  description: "An Iot Development Environment"
  license: MIT
